### ISSUE TITLE
CPU high when probe init

### ISSUE THREAD

**Issue by chriskaliX** [ehids/ebpfmanager#16]
**Describe the bug**

CPU is high when my program loaded and goes low after few seconds. 

![image](https://user-images.githubusercontent.com/46471110/181297718-bf853ce1-5ba7-4c38-8141-cceb640e4c4b.png)

**Details**

```
manager.go L549 m.loadCollection()
manager.go L1339 probe.Init(m)
...
probe.go L357 GetSyscallFnNameWithSymFile
utils.go L125 getSyscallName
```
In my situation, I hook multiple kprobes, and call `getSyscallName` multiple times. And every time, we read `/proc/kallsyms`, which is 5.5M in my machine, and do a regex for the whole string.

**Comment by chriskaliX** [comment]
Maybe we can do these:
1. Load the `/proc/kallsyms` once during `InitWithOptions`
2. Get all the functions name in one loop
3. Create a new function with a delay in the loop for some performance sensitive situation

**Comment by cfc4n** [comment]
oops...

Is save `/proc/kallsyms` to memory cache a good idea?

**Comment by chriskaliX** [comment]
Maybe not. But the way that datadog does looks good to me. In kprobe situation, we only need to get the proper prefix, once we get it, we don't need to go through the /proc/kallsyms again. Maybe if we remove the `utils.go L100~L103`, it would be better.
And in `utils.go getSyscallFnNameWithKallsyms`, there are lots of `FindAllString`, I think maybe `Find` is better ? 🤨

**Comment by chriskaliX** [comment]
This will take some time
