### ISSUE TITLE
针对FindFilterFunction适配内核未开启DEBUG_FS的情况

### ISSUE THREAD

**Issue by SeeFlowerX** [ehids/ebpfmanager#30]
在Android上，如果内核未开启DEBUG_FS的时候，没有`/sys/kernel/debug`目录，如果使用ebpfmanager编写程序，那么将无法运行任何kretprobe/kprobe程序

同时内核未开启DEBUG_FS的时候，`/sys/kernel/tracing`下面也没有名为`available_filter_functions`的文件

可以考虑通过读取`/proc/kallsyms`来作为fallback方案获取信息？

- [Use /proc/kallsyms for regex filtering ](https://github.com/iovisor/bcc/pull/1540)

**Comment by SeeFlowerX** [comment]
其实是有读取`/proc/kallsyms`的，但是在没有上面的debug目录的时候，提前返回了

https://github.com/gojue/ebpfmanager/blob/801c6554cae79815b9b56d2332064eb4bda7e461/probe.go#L382

**Comment by cfc4n** [comment]
感谢反馈，我近期看下二者之间的差异。

你测试过在未开启`DEBUG_FS`下，自己改为`/proc/kallsyms`的效果吗？

**Comment by SeeFlowerX** [comment]
我没有做什么修改，仅仅是将上面那一行`return err`注释调，然后编译使用，没有什么问题。

不过我仍然在使用[ebpfmanager v0.3.0](https://github.com/gojue/ebpfmanager/releases/tag/v0.3.0)，没有在最新版上测试过。

**Comment by cfc4n** [comment]
pr里提了，辛苦试试。
