### ISSUE TITLE
checksum 问题

### ISSUE THREAD

**Issue by veo** [ehids/ebpfmanager#38]
我写了一个xdp的程序，修改了端口信息，发现UDP包可以正常使用，但是TCP无法使用

根据搜索了解可能是sum没有校验通过的问题？

bpf_helpers.h 内并没有ipv4_csum类似的函数，从网上找了很多其他人写的代码，也无法使用

大佬可以请教一下这个问题怎么解决吗？是不是checksum的问题？

**Comment by cfc4n** [comment]
`bpf_csum_*`等csum函数挺多的，都是bpf内置的。   用法上，可以搜一下，很多。


https://github.com/facebookincubator/katran/blob/main/katran/lib/bpf/csum_helpers.h

https://github.com/tklauser/cilium/blob/main/bpf/lib/csum.h

**Comment by veo** [comment]
代码类似，udp正常，tcp不正常，是不是大概率是checksum的问题呢？有没有什么调试方法能够判断？因为目前只看到tcp不正常也不知道是不是sum的问题

**Comment by veo** [comment]
找到方法了，用tcpdump -ev参数可以看到 sum incorrect，用了网上各种csum函数都不行，头疼

**Comment by cfc4n** [comment]
一般情况下csum错了，不影响tcp通讯。

**Comment by veo** [comment]
大佬方便加个好友吗？我刚开始学ebpf，想请教您一些问题

**Comment by cfc4n** [comment]
起码为社区做一些贡献吧。 比如 https://github.com/gojue/ecapture/pull/413#pullrequestreview-1727291836 这里的同学。 😂

**Comment by veo** [comment]
我再学学。。。刚接触

**Comment by veo** [comment]
等我解决这个问题我可以在这个项目试试写些example

**Comment by veo** [comment]
我已经把check sum都算对了，tcp本机端口转发还是失败，但是转发到其他机器可以，不是checksum的问题

只要是转发到本机，握手包只有syn，没有ack，不知道为什么

**Comment by cfc4n** [comment]
XDP只能读取ingress的包。 你修改的话，是不是要用TC或者其他类型？

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Netfilter-packet-flow.svg/1600px-Netfilter-packet-flow.svg.png)

![](https://cache.treehouse.systems/media_attachments/files/109/928/070/084/142/607/original/f1fbce7481e026ae.png)

![image](https://github.com/gojue/ebpfmanager/assets/709947/d28bdea8-09c8-454a-b9f7-fb9ed1834bd0)

**Comment by veo** [comment]
我是看了大佬你的这篇文章，参考了过防火墙的那部分技术，但是我无法复现
https://www.cnxct.com/evil-use-ebpf-and-how-to-detect-ebpf-rootkit-in-linux/

**Comment by veo** [comment]
找到原因了，TC改egress和ingress确实可以。我之前XDP本机改了无效的原因也找到了，因为收包的 tcp->dest 改变了，发包的时候要把 tcp->source 改回来才行，这样看XDP确实无法实现本机端口转发？

**Comment by veo** [comment]
那大佬的文章写的例子是怎么办到的- -

**Comment by cfc4n** [comment]
> 我是看了大佬你的这篇文章，参考了过防火墙的那部分技术，但是我无法复现 https://www.cnxct.com/evil-use-ebpf-and-how-to-detect-ebpf-rootkit-in-linux/

有一定的攻击性，不方便公开细节。 已经公开部分也有一定模糊。仅提供思路。

**Comment by cfc4n** [comment]
> 那大佬的文章写的例子是怎么办到的- -

公众号里给我发个消息。

**Comment by cucxbd** [comment]
> 我已经把check sum都算对了，tcp本机端口转发还是失败，但是转发到其他机器可以，不是checksum的问题
> 
> 只要是转发到本机，握手包只有syn，没有ack，不知道为什么

你好，请教一下是怎么计算的checksum，我也试了好多方法，结果都是bpf 校验器过不了

**Comment by veo** [comment]
> > 我已经把check sum都算对了，tcp本机端口转发还是失败，但是转发到其他机器可以，不是checksum的问题
> > 只要是转发到本机，握手包只有syn，没有ack，不知道为什么
> 
> 你好，请教一下是怎么计算的checksum，我也试了好多方法，结果都是bpf 校验器过不了

从网上搜得到很多算checksum的。我有点忘记了，我当时的问题不是checksum的问题，好像checksum算错也是可以通信的，好像奥
