### ISSUE TITLE
无法加载LSM类型的ebpf

### ISSUE THREAD

**Issue by realsyy** [ehids/ebpfmanager#39]
加载LSM类型的ebpf时，func (p *Probe) attach()函数报错，"program type LSM not implemented yet"。

**Comment by cfc4n** [comment]
嗯，确实还不支持，你可以研发这个功能，并提一个pr吗？

**Comment by realsyy** [comment]
@cfc4n 我在probe.go文件里面增加一个函数：
// attachLsm - Attaches the probe to its lsm hook
func (p *Probe) attachLsm() error {
	link, err := link.AttachLSM(link.LSMOptions{Program: p.program})
	if err != nil {
		return errors.New(fmt.Sprintf("error:%v , couldn's activate lsm %s, matchFuncName:%s", err, p.Section, p.EbpfFuncName))
	}
	p.link = link
	return nil
}
在probe.go文件中的attach()函数里面增加了调用语句：
	case ebpf.LSM:
		err = p.attachLsm()
就能加载LSM类型的ebp了。

**Comment by cfc4n** [comment]
能找个环境验证一下吗？

**Comment by realsyy** [comment]
验证了。
ebpf程序：
![1701417550739](https://github.com/gojue/ebpfmanager/assets/150642683/3b02e0ed-90fb-460d-88fd-9241720b4b4e)
结果：
![1701417682152](https://github.com/gojue/ebpfmanager/assets/150642683/d4c517cb-fe3a-47b6-a8fc-bbdf190be766)
![1701417727426](https://github.com/gojue/ebpfmanager/assets/150642683/86175574-212b-40d7-b698-350ebe8161ae)

**Comment by cfc4n** [comment]
确实可用，感谢。 

不过，你可以提一个PR吗？

除了在probe.go文件增加LSM的HOOK之外，还需要在`/examples/programs`下增加一个`lsm`目录，并创建一个测试程序。 这个测试程序需要先检测当前系统内核，不支持LSM的话，就不用执行了。

这样，每次提交代码时，Github Action就可以运行这个测试，更好地保证项目质量。
