### ISSUE TITLE
能否支持动态修改probe

### ISSUE THREAD

**Issue by kelpiezqc** [ehids/ebpfmanager#46]
比如这个uprobe demo
https://github.com/gojue/ebpfmanager/blob/master/examples/programs/uprobe/main.go#L9

已经运行了这个Manager，想要在Probes中再加一个Probe，能否动态实现？

**Comment by cfc4n** [comment]
参考 https://github.com/gojue/ebpfmanager/blob/11525325c96c65722b2c2096fce73ba9122bb922/examples/clone_vs_add_hook/demo.go#L48

**Comment by kelpiezqc** [comment]
it works!
